language: java
sudo: required
dist: trusty
install: true

jdk:
- oraclejdk8
- openjdk8
- openjdk10
- oraclejdk11
- openjdk11

script:
- mvn -e -U clean package

cache:
  directories:
    - $HOME/.m2/repository
